<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
        <RootNamespace>Meshmakers.Octo.Communication.EdgeAdapter.Demo.Tests</RootNamespace>
        <OutputPath>..\..\bin\$(Configuration)\</OutputPath>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FakeItEasy" Version="9.0.1"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageReference Include="xunit.v3.mtp-off" Version="4.0.0"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\AdapterEdgeDemo\AdapterEdgeDemo.csproj"/>
    </ItemGroup>

</Project>
